<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WfAssist.AspNetCore</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="FluentMigrator" Version="7.1.0" />
      <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
      <PackageReference Include="FluentMigrator.Runner.SQLite" Version="7.1.0" />
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
      <PackageReference Include="OneOf" Version="3.0.271" />
    </ItemGroup>

</Project>
