<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>WfAssist.AspNetCore</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="FluentMigrator" Version="7.1.0" />
        <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
        <PackageReference Include="FluentMigrator.Runner.SQLite" Version="7.1.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="JsonPath.Net" Version="2.1.1" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
        <PackageReference Include="OneOf" Version="3.0.271" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.10.3" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="server.lib.tests" />
        <InternalsVisibleTo Include="_server.host.openapi" />
    </ItemGroup>

</Project>
