// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiWorkflowsByIdData, DeleteApiWorkflowsByIdResponses, GetApiExecutionsByIdData, GetApiExecutionsByIdErrors, GetApiExecutionsByIdResponses, GetApiExecutionsData, GetApiExecutionsResponses, GetApiWorkflowsByIdData, GetApiWorkflowsByIdErrors, GetApiWorkflowsByIdResponses, GetApiWorkflowsEventsData, GetApiWorkflowsEventsResponse, GetApiWorkflowsEventsResponses, GetApiWorkflowsIdentitiesData, GetApiWorkflowsIdentitiesResponses, PostApiWorkflowsByIdQueueExecutionData, PostApiWorkflowsByIdQueueExecutionErrors, PostApiWorkflowsByIdQueueExecutionResponses, PostApiWorkflowsByIdRenameData, PostApiWorkflowsByIdRenameErrors, PostApiWorkflowsByIdRenameResponses, PostApiWorkflowsByIdUpdateDataData, PostApiWorkflowsByIdUpdateDataErrors, PostApiWorkflowsByIdUpdateDataResponses, PostApiWorkflowsData, PostApiWorkflowsErrors, PostApiWorkflowsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiExecutions = <ThrowOnError extends boolean = false>(options?: Options<GetApiExecutionsData, ThrowOnError>): RequestResult<GetApiExecutionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiExecutionsResponses, unknown, ThrowOnError>({ url: '/api/executions', ...options });

export const getApiExecutionsById = <ThrowOnError extends boolean = false>(options: Options<GetApiExecutionsByIdData, ThrowOnError>): RequestResult<GetApiExecutionsByIdResponses, GetApiExecutionsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetApiExecutionsByIdResponses, GetApiExecutionsByIdErrors, ThrowOnError>({ url: '/api/executions/{id}', ...options });

export const getApiWorkflowsIdentities = <ThrowOnError extends boolean = false>(options?: Options<GetApiWorkflowsIdentitiesData, ThrowOnError>): RequestResult<GetApiWorkflowsIdentitiesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiWorkflowsIdentitiesResponses, unknown, ThrowOnError>({ url: '/api/workflows/identities', ...options });

export const deleteApiWorkflowsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiWorkflowsByIdData, ThrowOnError>): RequestResult<DeleteApiWorkflowsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteApiWorkflowsByIdResponses, unknown, ThrowOnError>({ url: '/api/workflows/{id}', ...options });

export const getApiWorkflowsById = <ThrowOnError extends boolean = false>(options: Options<GetApiWorkflowsByIdData, ThrowOnError>): RequestResult<GetApiWorkflowsByIdResponses, GetApiWorkflowsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetApiWorkflowsByIdResponses, GetApiWorkflowsByIdErrors, ThrowOnError>({ url: '/api/workflows/{id}', ...options });

export const postApiWorkflows = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsData, ThrowOnError>): RequestResult<PostApiWorkflowsResponses, PostApiWorkflowsErrors, ThrowOnError> => (options.client ?? client).post<PostApiWorkflowsResponses, PostApiWorkflowsErrors, ThrowOnError>({
    url: '/api/workflows',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiWorkflowsByIdRename = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsByIdRenameData, ThrowOnError>): RequestResult<PostApiWorkflowsByIdRenameResponses, PostApiWorkflowsByIdRenameErrors, ThrowOnError> => (options.client ?? client).post<PostApiWorkflowsByIdRenameResponses, PostApiWorkflowsByIdRenameErrors, ThrowOnError>({
    url: '/api/workflows/{id}/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiWorkflowsByIdUpdateData = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsByIdUpdateDataData, ThrowOnError>): RequestResult<PostApiWorkflowsByIdUpdateDataResponses, PostApiWorkflowsByIdUpdateDataErrors, ThrowOnError> => (options.client ?? client).post<PostApiWorkflowsByIdUpdateDataResponses, PostApiWorkflowsByIdUpdateDataErrors, ThrowOnError>({
    url: '/api/workflows/{id}/updateData',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiWorkflowsEvents = <ThrowOnError extends boolean = false>(options?: Options<GetApiWorkflowsEventsData, ThrowOnError, GetApiWorkflowsEventsResponse>): Promise<ServerSentEventsResult<GetApiWorkflowsEventsResponses>> => (options?.client ?? client).sse.get<GetApiWorkflowsEventsResponses, unknown, ThrowOnError>({ url: '/api/workflows/events', ...options });

export const postApiWorkflowsByIdQueueExecution = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsByIdQueueExecutionData, ThrowOnError>): RequestResult<PostApiWorkflowsByIdQueueExecutionResponses, PostApiWorkflowsByIdQueueExecutionErrors, ThrowOnError> => (options.client ?? client).post<PostApiWorkflowsByIdQueueExecutionResponses, PostApiWorkflowsByIdQueueExecutionErrors, ThrowOnError>({ url: '/api/workflows/{id}/queueExecution', ...options });
