// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiWorkflowsByIdData, DeleteApiWorkflowsByIdResponses, GetApiExecutionsData, GetApiExecutionsResponses, GetApiWorkflowsByIdData, GetApiWorkflowsByIdErrors, GetApiWorkflowsByIdResponses, GetApiWorkflowsEventsData, GetApiWorkflowsEventsResponses, GetApiWorkflowsIdentitiesData, GetApiWorkflowsIdentitiesResponses, PostApiWorkflowsByIdQueueExecutionData, PostApiWorkflowsByIdQueueExecutionErrors, PostApiWorkflowsByIdQueueExecutionResponses, PostApiWorkflowsByIdRenameData, PostApiWorkflowsByIdRenameErrors, PostApiWorkflowsByIdRenameResponses, PostApiWorkflowsByIdUpdateDataData, PostApiWorkflowsByIdUpdateDataErrors, PostApiWorkflowsByIdUpdateDataResponses, PostApiWorkflowsData, PostApiWorkflowsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiExecutions = <ThrowOnError extends boolean = false>(options?: Options<GetApiExecutionsData, ThrowOnError>) => (options?.client ?? client).get<GetApiExecutionsResponses, unknown, ThrowOnError>({ url: '/api/executions', ...options });

export const getApiWorkflowsIdentities = <ThrowOnError extends boolean = false>(options?: Options<GetApiWorkflowsIdentitiesData, ThrowOnError>) => (options?.client ?? client).get<GetApiWorkflowsIdentitiesResponses, unknown, ThrowOnError>({ url: '/api/workflows/identities', ...options });

export const deleteApiWorkflowsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiWorkflowsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiWorkflowsByIdResponses, unknown, ThrowOnError>({ url: '/api/workflows/{id}', ...options });

export const getApiWorkflowsById = <ThrowOnError extends boolean = false>(options: Options<GetApiWorkflowsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiWorkflowsByIdResponses, GetApiWorkflowsByIdErrors, ThrowOnError>({ url: '/api/workflows/{id}', ...options });

export const postApiWorkflows = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsData, ThrowOnError>) => (options.client ?? client).post<PostApiWorkflowsResponses, unknown, ThrowOnError>({
    url: '/api/workflows',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiWorkflowsByIdRename = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsByIdRenameData, ThrowOnError>) => (options.client ?? client).post<PostApiWorkflowsByIdRenameResponses, PostApiWorkflowsByIdRenameErrors, ThrowOnError>({
    url: '/api/workflows/{id}/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiWorkflowsByIdUpdateData = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsByIdUpdateDataData, ThrowOnError>) => (options.client ?? client).post<PostApiWorkflowsByIdUpdateDataResponses, PostApiWorkflowsByIdUpdateDataErrors, ThrowOnError>({
    url: '/api/workflows/{id}/updateData',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiWorkflowsEvents = <ThrowOnError extends boolean = false>(options?: Options<GetApiWorkflowsEventsData, ThrowOnError>) => (options?.client ?? client).sse.get<GetApiWorkflowsEventsResponses, unknown, ThrowOnError>({ url: '/api/workflows/events', ...options });

export const postApiWorkflowsByIdQueueExecution = <ThrowOnError extends boolean = false>(options: Options<PostApiWorkflowsByIdQueueExecutionData, ThrowOnError>) => (options.client ?? client).post<PostApiWorkflowsByIdQueueExecutionResponses, PostApiWorkflowsByIdQueueExecutionErrors, ThrowOnError>({ url: '/api/workflows/{id}/queueExecution', ...options });
