// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateWorkflowRequest = {
    name: string;
    data: WorkflowDataDto;
};

export type ExecutionStatus = 'Queued' | 'Running' | 'Completed' | 'Failed';

export type GetIdentitiesResponse = {
    identities: Array<WorkFlowIdentityDto>;
};

export type GetWorkflowByIdResponse = {
    item: WorkflowDto;
};

export type HttpHeaderDto = {
    name: string;
    value: string;
};

export type Notification = ({
    type?: 'WorkflowExecutionStarted';
} & NotificationWorkflowExecutionStarted) | ({
    type?: 'WorkflowExecutionEnded';
} & NotificationWorkflowExecutionEnded);

export type NotificationWorkflowExecutionEnded = {
    type?: 'WorkflowExecutionEnded';
    executionId: string;
    workflowId: string;
    workflowName: string;
    status: ExecutionStatus;
};

export type NotificationWorkflowExecutionStarted = {
    type?: 'WorkflowExecutionStarted';
    executionId: string;
    workflowId: string;
    workflowName: string;
};

export type PositionDto = {
    x: number;
    y: number;
};

export type RenameWorkflowRequest = {
    newName: string;
};

export type RequestTypeDto = 'Get' | 'Post' | 'Put' | 'Patch' | 'Delete';

export type RunWorkflowResponse = {
    runId: string;
};

export type SseItemOfNotification = {
    data?: Notification;
    eventType?: null | string;
    eventId?: null | string;
    reconnectionInterval?: null | string;
};

export type UpdateWorkflowDataRequest = {
    data: WorkflowDataDto;
};

export type WorkflowDataDto = {
    nodes?: Array<WorkflowNodeDto>;
    edges?: Array<WorkflowEdgeDto>;
};

export type WorkflowDto = {
    id: string;
    name: string;
    data: WorkflowDataDto;
};

export type WorkflowEdgeDto = {
    id: string;
    source: string;
    target: string;
};

export type WorkFlowIdentityDto = {
    id: string;
    name: string;
};

export type WorkflowNodeDataDto = ({
    type?: 'Request';
} & WorkflowNodeDataDtoRequestNodeDataDto) | ({
    type?: 'Headers';
} & WorkflowNodeDataDtoHeadersNodeDataDto);

export type WorkflowNodeDataDtoHeadersNodeDataDto = {
    type?: 'Headers';
    headers?: Array<HttpHeaderDto>;
};

export type WorkflowNodeDataDtoRequestNodeDataDto = {
    type?: 'Request';
    requestType: RequestTypeDto;
    url: string;
    requestBody?: null | string;
};

export type WorkflowNodeDto = {
    id: string;
    position: PositionDto;
    data: WorkflowNodeDataDto;
};

export type GetWfAssistWorkflowsIdentitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wfAssist/workflows/identities';
};

export type GetWfAssistWorkflowsIdentitiesResponses = {
    /**
     * OK
     */
    200: GetIdentitiesResponse;
};

export type GetWfAssistWorkflowsIdentitiesResponse = GetWfAssistWorkflowsIdentitiesResponses[keyof GetWfAssistWorkflowsIdentitiesResponses];

export type DeleteWfAssistWorkflowsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/wfAssist/workflows/{id}';
};

export type DeleteWfAssistWorkflowsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteWfAssistWorkflowsByIdResponse = DeleteWfAssistWorkflowsByIdResponses[keyof DeleteWfAssistWorkflowsByIdResponses];

export type GetWfAssistWorkflowsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/wfAssist/workflows/{id}';
};

export type GetWfAssistWorkflowsByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetWfAssistWorkflowsByIdResponses = {
    /**
     * OK
     */
    200: GetWorkflowByIdResponse;
};

export type GetWfAssistWorkflowsByIdResponse = GetWfAssistWorkflowsByIdResponses[keyof GetWfAssistWorkflowsByIdResponses];

export type PostWfAssistWorkflowsData = {
    body: CreateWorkflowRequest;
    path?: never;
    query?: never;
    url: '/wfAssist/workflows';
};

export type PostWfAssistWorkflowsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostWfAssistWorkflowsResponse = PostWfAssistWorkflowsResponses[keyof PostWfAssistWorkflowsResponses];

export type PostWfAssistWorkflowsByIdRenameData = {
    body: RenameWorkflowRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/wfAssist/workflows/{id}/rename';
};

export type PostWfAssistWorkflowsByIdRenameErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostWfAssistWorkflowsByIdRenameResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostWfAssistWorkflowsByIdRenameResponse = PostWfAssistWorkflowsByIdRenameResponses[keyof PostWfAssistWorkflowsByIdRenameResponses];

export type PostWfAssistWorkflowsByIdUpdateDataData = {
    body: UpdateWorkflowDataRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/wfAssist/workflows/{id}/updateData';
};

export type PostWfAssistWorkflowsByIdUpdateDataErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostWfAssistWorkflowsByIdUpdateDataResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostWfAssistWorkflowsByIdUpdateDataResponse = PostWfAssistWorkflowsByIdUpdateDataResponses[keyof PostWfAssistWorkflowsByIdUpdateDataResponses];

export type GetWfAssistWorkflowsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wfAssist/workflows/events';
};

export type GetWfAssistWorkflowsEventsResponses = {
    /**
     * OK
     */
    200: SseItemOfNotification;
};

export type GetWfAssistWorkflowsEventsResponse = GetWfAssistWorkflowsEventsResponses[keyof GetWfAssistWorkflowsEventsResponses];

export type PostWfAssistWorkflowsByIdQueueRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/wfAssist/workflows/{id}/queueRun';
};

export type PostWfAssistWorkflowsByIdQueueRunErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostWfAssistWorkflowsByIdQueueRunResponses = {
    /**
     * OK
     */
    200: RunWorkflowResponse;
};

export type PostWfAssistWorkflowsByIdQueueRunResponse = PostWfAssistWorkflowsByIdQueueRunResponses[keyof PostWfAssistWorkflowsByIdQueueRunResponses];
