// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateWorkflowRequest = {
    name: string;
    data: WorkflowDataDto;
};

export type EdgeDto = {
    id: string;
    source: string;
    target: string;
};

export type ExecutionStatus = 'Queued' | 'Running' | 'Completed' | 'Failed';

export type GetIdentitiesResponse = {
    identities: Array<WorkFlowIdentityDto>;
};

export type GetWorkflowByIdResponse = {
    item: WorkflowDto;
};

export type GetWorkflowExecutionByIdResponse = {
    id: string;
    status: ExecutionStatus;
    dataSnapshot: JsonDocument;
    processingResults?: {
        [key: string]: ProcessingResult;
    };
};

export type GetWorkflowExecutionsResponse = {
    items: Array<WorkflowExecutionDto>;
};

export type HttpHeaderDto = {
    name: string;
    value: string;
};

export type JsonDocument = unknown;

export type NodeDto = ({
    type?: 'RequestNode';
} & NodeDtoRequestNodeDto) | ({
    type?: 'HeadersNode';
} & NodeDtoHeadersNodeDto);

export type NodeDtoHeadersNodeDto = {
    type?: 'HeadersNode';
    headers?: Array<HttpHeaderDto>;
    id: string;
    position: PositionDto;
};

export type NodeDtoRequestNodeDto = {
    type?: 'RequestNode';
    requestType: RequestTypeDto;
    url: string;
    requestBody?: null | string;
    id: string;
    position: PositionDto;
};

export type Notification = ({
    type?: 'WorkflowExecutionEnded';
} & NotificationWorkflowExecutionEnded) | ({
    type?: 'WorkflowExecutionStarted';
} & NotificationWorkflowExecutionStarted);

export type NotificationWorkflowExecutionEnded = {
    type?: 'WorkflowExecutionEnded';
    executionId: string;
    workflowId: string;
    workflowName: string;
    status: string;
};

export type NotificationWorkflowExecutionStarted = {
    type?: 'WorkflowExecutionStarted';
    executionId: string;
    workflowId: string;
    workflowName: string;
};

export type PositionDto = {
    x: number;
    y: number;
};

export type ProcessingResult = {
    isSuccessful: boolean;
    valueType: ProcessResultValueType;
    data?: unknown;
    errorMessage?: null | string;
};

export type ProcessResultValueType = 'None' | 'JsonDocument' | 'Error';

export type RenameWorkflowRequest = {
    newName: string;
};

export type RequestTypeDto = 'Get' | 'Post' | 'Put' | 'Patch' | 'Delete';

export type RunWorkflowResponse = {
    runId: string;
};

export type SseItemOfNotification = {
    data?: Notification;
    eventType?: null | string;
    eventId?: null | string;
    reconnectionInterval?: null | string;
};

export type UpdateWorkflowDataRequest = {
    data: WorkflowDataDto;
};

export type WorkflowDataDto = {
    nodes?: Array<NodeDto>;
    edges?: Array<EdgeDto>;
};

export type WorkflowDto = {
    id: string;
    name: string;
    data: WorkflowDataDto;
};

export type WorkflowExecutionDto = {
    id: string;
    status: ExecutionStatus;
    dataSnapshot: JsonDocument;
    processingResults?: {
        [key: string]: ProcessingResult;
    };
};

export type WorkFlowIdentityDto = {
    id: string;
    name: string;
};

export type GetApiExecutionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/executions';
};

export type GetApiExecutionsResponses = {
    /**
     * OK
     */
    200: GetWorkflowExecutionsResponse;
};

export type GetApiExecutionsResponse = GetApiExecutionsResponses[keyof GetApiExecutionsResponses];

export type GetApiExecutionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/executions/{id}';
};

export type GetApiExecutionsByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiExecutionsByIdResponses = {
    /**
     * OK
     */
    200: GetWorkflowExecutionByIdResponse;
};

export type GetApiExecutionsByIdResponse = GetApiExecutionsByIdResponses[keyof GetApiExecutionsByIdResponses];

export type GetApiWorkflowsIdentitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workflows/identities';
};

export type GetApiWorkflowsIdentitiesResponses = {
    /**
     * OK
     */
    200: GetIdentitiesResponse;
};

export type GetApiWorkflowsIdentitiesResponse = GetApiWorkflowsIdentitiesResponses[keyof GetApiWorkflowsIdentitiesResponses];

export type DeleteApiWorkflowsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workflows/{id}';
};

export type DeleteApiWorkflowsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiWorkflowsByIdResponse = DeleteApiWorkflowsByIdResponses[keyof DeleteApiWorkflowsByIdResponses];

export type GetApiWorkflowsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workflows/{id}';
};

export type GetApiWorkflowsByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiWorkflowsByIdResponses = {
    /**
     * OK
     */
    200: GetWorkflowByIdResponse;
};

export type GetApiWorkflowsByIdResponse = GetApiWorkflowsByIdResponses[keyof GetApiWorkflowsByIdResponses];

export type PostApiWorkflowsData = {
    body: CreateWorkflowRequest;
    path?: never;
    query?: never;
    url: '/api/workflows';
};

export type PostApiWorkflowsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiWorkflowsResponse = PostApiWorkflowsResponses[keyof PostApiWorkflowsResponses];

export type PostApiWorkflowsByIdRenameData = {
    body: RenameWorkflowRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workflows/{id}/rename';
};

export type PostApiWorkflowsByIdRenameErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiWorkflowsByIdRenameResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiWorkflowsByIdRenameResponse = PostApiWorkflowsByIdRenameResponses[keyof PostApiWorkflowsByIdRenameResponses];

export type PostApiWorkflowsByIdUpdateDataData = {
    body: UpdateWorkflowDataRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workflows/{id}/updateData';
};

export type PostApiWorkflowsByIdUpdateDataErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiWorkflowsByIdUpdateDataResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiWorkflowsByIdUpdateDataResponse = PostApiWorkflowsByIdUpdateDataResponses[keyof PostApiWorkflowsByIdUpdateDataResponses];

export type GetApiWorkflowsEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workflows/events';
};

export type GetApiWorkflowsEventsResponses = {
    /**
     * OK
     */
    200: SseItemOfNotification;
};

export type GetApiWorkflowsEventsResponse = GetApiWorkflowsEventsResponses[keyof GetApiWorkflowsEventsResponses];

export type PostApiWorkflowsByIdQueueExecutionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/workflows/{id}/queueExecution';
};

export type PostApiWorkflowsByIdQueueExecutionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiWorkflowsByIdQueueExecutionResponses = {
    /**
     * OK
     */
    200: RunWorkflowResponse;
};

export type PostApiWorkflowsByIdQueueExecutionResponse = PostApiWorkflowsByIdQueueExecutionResponses[keyof PostApiWorkflowsByIdQueueExecutionResponses];
