<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>wf-assist</Title>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>WfAssist</PackageId>
        <PackageVersion>0.0.1-dev</PackageVersion>
        <PackageOutputPath>$(MSBuildProjectDirectory)/packages</PackageOutputPath>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>

    <!-- Copy referenced project binaries to package -->
    <Target DependsOnTargets="ResolveReferences" Name="CopyProjectReferencesToPackage">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths->WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))"/>
        </ItemGroup>
    </Target>

    <!-- Build client and include its binaries to package -->
    <Target Name="BuildAndIncludeClient" BeforeTargets="BeforeBuild">
        <Exec Command="bun run build" WorkingDirectory="$(MSBuildProjectDirectory)/../client/" />
        <ItemGroup>
            <Content Include="$(MSBuildProjectDirectory)/../client/dist/**/*.*">
                <Pack>true</Pack>
                <PackagePath>wwwroot</PackagePath>
                <PackageCopyToOutput>true</PackageCopyToOutput>
            </Content>
        </ItemGroup>
    </Target>

    <ItemGroup>
        <!-- Transitive build targets like copying nuget contents to project output directory on build, etc. -->
        <None Include="buildTransitive\WfAssist.targets" Pack="true" PackagePath="buildTransitive\WfAssist.targets" />

        <ProjectReference Include="..\server\AspNetCore.App\AspNetCore.App.csproj" IncludeAssets="all" />
    </ItemGroup>
</Project>
