<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WfAssist.Executions</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Executions.Contracts\Executions.Contracts.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
