// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { deleteWfAssistWorkflowsById, getWfAssistWorkflowsById, getWfAssistWorkflowsIdentities, type Options, postWfAssistWorkflows, postWfAssistWorkflowsByIdRename, postWfAssistWorkflowsByIdUpdateData } from '../sdk.gen';
import type { DeleteWfAssistWorkflowsByIdData, DeleteWfAssistWorkflowsByIdResponse, GetWfAssistWorkflowsByIdData, GetWfAssistWorkflowsIdentitiesData, PostWfAssistWorkflowsByIdRenameData, PostWfAssistWorkflowsByIdRenameResponse, PostWfAssistWorkflowsByIdUpdateDataData, PostWfAssistWorkflowsByIdUpdateDataResponse, PostWfAssistWorkflowsData, PostWfAssistWorkflowsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getWfAssistWorkflowsIdentitiesQueryKey = (options?: Options<GetWfAssistWorkflowsIdentitiesData>) => createQueryKey('getWfAssistWorkflowsIdentities', options);

export const getWfAssistWorkflowsIdentitiesQuery = (options?: Options<GetWfAssistWorkflowsIdentitiesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWfAssistWorkflowsIdentities({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWfAssistWorkflowsIdentitiesQueryKey(options)
    });
};

export const deleteWfAssistWorkflowsByIdMutation = (options?: Partial<Options<DeleteWfAssistWorkflowsByIdData>>): MutationOptions<DeleteWfAssistWorkflowsByIdResponse, DefaultError, Options<DeleteWfAssistWorkflowsByIdData>> => {
    const mutationOptions: MutationOptions<DeleteWfAssistWorkflowsByIdResponse, DefaultError, Options<DeleteWfAssistWorkflowsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteWfAssistWorkflowsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWfAssistWorkflowsByIdQueryKey = (options: Options<GetWfAssistWorkflowsByIdData>) => createQueryKey('getWfAssistWorkflowsById', options);

export const getWfAssistWorkflowsByIdQuery = (options: Options<GetWfAssistWorkflowsByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getWfAssistWorkflowsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getWfAssistWorkflowsByIdQueryKey(options)
    });
};

export const postWfAssistWorkflowsMutation = (options?: Partial<Options<PostWfAssistWorkflowsData>>): MutationOptions<PostWfAssistWorkflowsResponse, DefaultError, Options<PostWfAssistWorkflowsData>> => {
    const mutationOptions: MutationOptions<PostWfAssistWorkflowsResponse, DefaultError, Options<PostWfAssistWorkflowsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWfAssistWorkflows({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postWfAssistWorkflowsByIdRenameMutation = (options?: Partial<Options<PostWfAssistWorkflowsByIdRenameData>>): MutationOptions<PostWfAssistWorkflowsByIdRenameResponse, DefaultError, Options<PostWfAssistWorkflowsByIdRenameData>> => {
    const mutationOptions: MutationOptions<PostWfAssistWorkflowsByIdRenameResponse, DefaultError, Options<PostWfAssistWorkflowsByIdRenameData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWfAssistWorkflowsByIdRename({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postWfAssistWorkflowsByIdUpdateDataMutation = (options?: Partial<Options<PostWfAssistWorkflowsByIdUpdateDataData>>): MutationOptions<PostWfAssistWorkflowsByIdUpdateDataResponse, DefaultError, Options<PostWfAssistWorkflowsByIdUpdateDataData>> => {
    const mutationOptions: MutationOptions<PostWfAssistWorkflowsByIdUpdateDataResponse, DefaultError, Options<PostWfAssistWorkflowsByIdUpdateDataData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postWfAssistWorkflowsByIdUpdateData({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
